enabled-by-default: true
cooldown-ms: 200
max-blocks-per-chain: 20
breaks-per-tick: 16

world-blacklist: []

y-min: -64
y-max: 320

matching:
  exact-blockdata: false

tools:
  whitelist: []

blocks:
  same-material-whitelist:
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
    - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - ANCIENT_DEBRIS
    - SAND
    - RED_SAND
    - GRAVEL
    - CLAY
    - SNOW
    - SNOW_BLOCK
    - POWDER_SNOW

tree:
  enabled: true
  break-leaves: false

messages:
  notify-chain-count: true
